### PR TITLE
Allow attributes after #[timeout]

### PR DESCRIPTION
**Pull request by Darksonn**
Closes: #27
Closes: https://github.com/tokio-rs/tokio/issues/6610

### CODE REVIEW

**Comment by Darksonn** [comment]
Ah, I guess this only fixes the issue with `#[timeout]`. If there are also cases where `#[test_case]` doesn't work, then that would be separate.

**Comment by Darksonn** [comment]
Actually, looks like it has never worked with `#[test_case]`. Using the old version of Tokio, we get:
```rs
#[tokio::test]
#[test_case(10)]
async fn timeout(arg: i32) {
    assert!(arg != 12);
}
```
```text
error: functions used as tests can not have any arguments
  --> src/main.rs:9:7
   |
9  |   async fn timeout(arg: i32) {
   |  _______^
10 | |     assert!(arg != 12);
11 | | }
   | |_^
```
and
```rs
#[test_case(10)]
#[tokio::test]
async fn timeout(arg: i32) {
    assert!(arg != 12);
}
```
```text
error: custom attribute panicked
 --> src/main.rs:7:1
  |
7 | #[test_case(10)]
  | ^^^^^^^^^^^^^^^^
  |
  = help: message: Expected identifier!
```

**Comment by Darksonn** [comment]
@zeenix You said that this used to work for you. Can you give a working example with `#[test_case]`?

**Comment by zeenix** [comment]
> @zeenix You said that this used to work for you. Can you give a working example with `#[test_case]`?

Sure, the failing pipeline I pointed to, was of the (unmerged) PR that upgrades tokio. All other jobs [have been passing](https://github.com/dbus2/busd/actions/runs/9280165428/job/25533978738). You can also just checkout busd and run `cargo t` in the main branch, if you want to reproduce locally (it should work on Linux, Windows and MacOs).

**Comment by Darksonn** [comment]
I cloned the repository you linked and searched for the string "test_case", but there are no results. I can only find uses of `#[timeout]`, not `#[test_case]`.

**Comment by zeenix** [comment]
> I cloned the repository you linked and searched for the string \"test_case\", but there are no results. I can only find uses of #[timeout], not #[test_case].

Oh `test_case`. No, I actually don't think I've ever used that. [My bug](https://github.com/tokio-rs/tokio/issues/6610#issue-2330633081) was only about `timeout`.

**Comment by zeenix** [comment]
> Are you able to verify that this PR fixes your issue?

I am happy to report that it does. :)

```
❯ cargo t
    Updating git repository `ssh://github.com/Darksonn/ntest.git`
   Compiling ntest_test_cases v0.9.2 (ssh://github.com/Darksonn/ntest.git?branch=alice/fix-attrs-after-timeout#f8d523e0)
   Compiling ntest_timeout v0.9.2 (ssh://github.com/Darksonn/ntest.git?branch=alice/fix-attrs-after-timeout#f8d523e0)
   Compiling ntest v0.9.2 (ssh://github.com/Darksonn/ntest.git?branch=alice/fix-attrs-after-timeout#f8d523e0)
   Compiling busd v0.3.1 (/home/zeenix/checkout/dbus2/busd)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 7.00s
     Running unittests src/lib.rs (target/debug/deps/busd-5ed485571a7a749c)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/bin/busd.rs (target/debug/deps/busd-ad2ae5830c2d6126)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/fdo.rs (target/debug/deps/fdo-8c241ea568e50b53)

running 1 test
test name_ownership_changes ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.41s

     Running tests/greet.rs (target/debug/deps/greet-218d32b8d0e2b4a9)

running 1 test
test greet ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.53s

     Running tests/monitor.rs (target/debug/deps/monitor-865400062e83e306)

running 1 test
test become_monitor ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

     Running tests/multiple_conns.rs (target/debug/deps/multiple_conns-dc3fc18a8809f289)

running 1 test
test multi_conenct ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s

   Doc-tests busd

running 0 tests
```

**Comment by zeenix** [comment]
I hope this wasn't forgotten. I want to use the latest tokio.

**Comment by becheran** [comment]
Sry for letting you wait. Looks good to me. Thanks for adding tests as well.

Will release a new version ASAP.

**Comment by becheran** [comment]
Fix is part of version `0.9.3`

**Pull request merged**
